on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:24

    steps:

      - name: Install Docker
        run: |
          apk add git docker

      - name: Login to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REGISTRY }}/${{ github.repository_owner }}/mmwe:latest
