issuer: "http://localhost:5556/dex"

web:
  http: "[::]:5556"

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

staticClients:
  - id: modern
    secret: secret
    name: 'Dex'
    redirectURIs:
      - 'http://localhost:8080/login/oauth2/code/dex'
    grant_types:
      - authorization_code
      - client_credentials

enablePasswordDB: true

# bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
# gotta double escape dollar signs in docker compose yaml

staticPasswords:
  - email: "admin@example.com"
    hash: '$2a$12$1QX6lUjKaJDqKoQ0GP72su.Ng5Eq3cKMdXjSA63iK.oBU8Bab6K9S'
    username: "admin"
    userID: "66891ddd-df19-42ce-8002-d2501312a599"

oauth2:
  skipApprovalScreen: true
