CREATE TABLE counters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(32) NOT NULL UNIQUE,
    counter_value bigint NOT NULL DEFAULT 0
);

INSERT INTO counters (name) VALUES ('default');
