name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: SemVer release
        id: release
        run: |
          cog changelog

      - name: Upload github release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          body: ${{ steps.release.outputs.stdout }}
          tag_name: ${{ github.ref_name }}
