name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: SemVer release
        id: release
        run: |
          cog changelog
        with:
          command: changelog
          args: --at ${{ github.ref_name }}

      - name: Upload github release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          body: ${{ steps.release.outputs.stdout }}
          tag_name: ${{ github.ref_name }}
