name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3

      - name: SemVer release
        id: release
        run: |
          cog changelog

      - name: Upload github release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          body: ${{ steps.release.outputs.stdout }}
          tag_name: ${{ github.ref_name }}
